export const sampleImages = {
  skin_disease: [
    { id: 'eczema_1', label: 'Eczema', path: '/samples/skin_disease/eczema_1.jpg' },
    { id: 'eczema_2', label: 'Eczema', path: '/samples/skin_disease/eczema_2.jpg' },
    { id: 'fungal_1', label: 'Fungal', path: '/samples/skin_disease/fungal_1.jpg' },
    { id: 'fungal_2', label: 'Fungal', path: '/samples/skin_disease/fungal_2.jpg' },
    { id: 'acne_1', label: 'Acne', path: '/samples/skin_disease/acne_1.jpg' },
    { id: 'acne_2', label: 'Acne', path: '/samples/skin_disease/acne_2.jpg' },
    { id: 'psoriasis_1', label: 'Psoriasis', path: '/samples/skin_disease/psoriasis_1.jpg' },
    { id: 'psoriasis_2', label: 'Psoriasis', path: '/samples/skin_disease/psoriasis_2.jpg' },
    { id: 'scabies_1', label: 'Scabies', path: '/samples/skin_disease/scabies_1.jpg' },
    { id: 'scabies_2', label: 'Scabies', path: '/samples/skin_disease/scabies_2.jpg' },
    { id: 'healthy_1', label: 'Healthy', path: '/samples/skin_disease/healthy_1.jpg' },
    { id: 'healthy_2', label: 'Healthy', path: '/samples/skin_disease/healthy_2.jpg' },
  ],
};

export const modelInfo = {
  skin_disease: {
    name: 'Skin Condition Analysis',
    description: 'Identifies common skin conditions from phone camera photos.',
    accuracy: '89%',
    classes: ['Acne', 'Eczema', 'Fungal', 'Healthy', 'Psoriasis', 'Scabies'],
    imageType: 'Skin Photo',
  },
};

export const conditionDescriptions = {
  eczema: 'Inflammatory skin condition causing red, itchy patches.',
  fungal: 'Fungal infection appearing as circular, scaly patches.',
  acne: 'Skin condition with pimples and inflamed bumps.',
  psoriasis: 'Autoimmune condition causing thick, scaly patches.',
  scabies: 'Parasitic infestation causing intense itching.',
  healthy: 'Normal skin without visible conditions.',
};

// Pre-cached LLM explanations (auto-generated by scripts/generate_explanations.py)
export const cachedExplanations = {
  skin_disease_acne_1: 'The skin shows multiple raised bumps with reddish and yellowish discoloration distributed across the cheek and temple area, displaying the characteristic inflammatory appearance typical of acne lesions with uneven texture and clustering pattern. The Model attention highlighting concentrates on several distinct bright spots corresponding to individual lesions on the cheek and forehead, with the most intense red and yellow activation marking the most prominent acne bumps.',
  skin_disease_acne_2: 'The skin displays multiple small, raised red and pink papules scattered across the forehead with a slightly uneven texture characteristic of inflammatory acne lesions. The Model attention highlighting shows concentrated red and yellow focus on the forehead region and around the glabellar area, corresponding to the locations of the most prominent acne lesions visible in the original image.',
  skin_disease_eczema_1: 'The skin displays redness, swelling, and a slightly rough or irritated texture characteristic of eczema, with the affected area showing inflammation and discoloration across the visible surface. The Model attention highlighting concentrates on the upper portions of the affected area and the edges of the inflamed region, identifying the most prominent sites of redness and swelling as key diagnostic features.',
  skin_disease_eczema_2: 'The skin shows areas of redness, inflammation, and roughened texture with an irregular, patchy distribution pattern characteristic of eczematous changes. The Model attention highlighting is concentrated on the inflamed red patches and areas of visible skin irritation, particularly clustered around the affected zones on the leg.',
  skin_disease_fungal_1: 'The skin shows multiple small, discrete, raised spots with a reddish appearance distributed across the surface, characteristic of a fungal infection pattern with clustered lesions. The Model attention highlighting concentrates on the bright yellow and red hot spots corresponding to the individual raised lesions and pustules scattered across the affected skin area.',
  skin_disease_fungal_2: 'The skin displays a circular patch with an erythematous border that appears raised and scaly, with a central area showing hyperpigmentation and a characteristic ring-like pattern typical of dermatophyte infection. The Model attention highlighting concentrates intensely on the central and peripheral edges of the lesion, with the brightest yellow and red focal points marking the border zone and scattered areas of active inflammation within the patch.',
  skin_disease_healthy_1: 'The skin displays a uniform peachy-brown tone with fine, even texture and no visible lesions, nodules, or irregular pigmentation patterns across the scanned area. The Model attention highlights are concentrated on several small, discrete circular spots distributed across the skin surface, suggesting the AI identified these focal points as characteristic features of healthy skin assessment.',
  skin_disease_healthy_2: 'The skin displays a uniform tan to light brown coloration with fine, evenly distributed hair follicles and a relatively smooth texture without visible lesions, discoloration, or abnormal patterns. The Model attention highlighting shows concentrated focus on discrete areas including a bright spot in the upper portion and a vertical linear region in the lower-left area, suggesting the model identified these specific features as key indicators of skin health.',
  skin_disease_psoriasis_1: 'The skin shows scattered brown to reddish macules and papules with a slightly rough texture distributed across the back, characteristic of psoriatic plaques with their typical erythematous and scaly appearance. The Model attention highlighting concentrates on the darker reddish lesions and clustered papules, particularly focusing on the grouped lesions in the upper right area and the isolated lesion on the lower left of the back.',
  skin_disease_psoriasis_2: 'The affected area displays a well-demarcated patch with a salmon-pink color, silvery-white scale coverage, and a slightly raised, thickened texture characteristic of psoriatic plaques, with irregular borders on what appears to be the elbow or knee region. The Model attention highlighting concentrates intensely on the central and peripheral zones of the plaque itself, with the brightest yellow-red activation corresponding to the most scaly and erythematous portions of the lesion.',
  skin_disease_scabies_1: 'The skin shows characteristic burrows and papules with a reddish, inflamed appearance distributed across the dorsal hand surface, appearing as small raised lesions with an erythematous base typical of scabies infestation. The Model attention highlighting concentrates on the discrete papular lesions and the areas between the fingers where the burrows are most prominent, indicating the AI model focused on these clustered inflammatory lesions as key diagnostic features.',
  skin_disease_scabies_2: 'The skin shows small, raised nodular lesions with a reddish appearance and irregular surface texture, distributed across the palm and finger areas with characteristic inflammatory changes consistent with scabies infestation. The Model attention highlighting concentrates on the prominent nodular bumps and raised lesions, particularly focusing on the most inflamed papular areas on the palm and between the fingers where the AI model identified the most diagnostically relevant features.',
};
